name: cl
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cython
  - pybind11
  - numpy
  - scipy
  - matplotlib
  - tqdm
  - networkx
  - numba
  - jax
  - jaxlib
  - cmocean
  - poisson_disc
  - vapory